apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}  # Size dynamically referenced from values.yaml
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  persistentVolumeSource:
    efs:
      fileSystemId: {{ .Values.persistence.efs.fileSystemId }}  # EFS FileSystem ID
      path: {{ .Values.persistence.efs.path }}  # Path to directory in EFS
      accessPoint: {{ .Values.persistence.efs.accessPoint | default "" }}  # Access point if defined
      readOnly: false  # EFS is read-write by default
  storageClassName: {{ .Values.persistence.storageClassName | quote }}  # Storage class (empty for EFS)
