apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  persistentVolumeSource:
    efs:
      fileSystemId: {{ .Values.persistence.efs.fileSystemId }}  # Correct field for EFS file system ID
      path: {{ .Values.persistence.efs.path }}  # Path on the EFS volume
      accessPoint: {{ .Values.persistence.efs.accessPoint | default "" }}  # Correctly use the access point if needed
      readOnly: false  # EFS is typically read-write
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
