apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  persistentVolumeSource:
    {{- if eq .Values.persistence.volumeType "efs" }}
    efs:
      fileSystemId: {{ .Values.persistence.efs.fileSystemId }}
      path: {{ .Values.persistence.efs.path }}
      accessPoint: {{ .Values.persistence.efs.accessPoint | default "" }}
      readOnly: false
    {{- end }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
