apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  persistentVolumeSource:
    efs:
      fileSystemId: {{ .Values.persistence.efs.server }}  # EFS file system ID (not URL)
      path: {{ .Values.persistence.efs.path }}           # Path within the EFS system
      readOnly: false
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
