apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
  - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  persistentVolumeSource:
    efs:
      fileSystemId: {{ .Values.persistence.efs.fileSystemId }}  # Use dynamic value for FileSystemId
      path: {{ .Values.persistence.efs.path }}  # Dynamic path
      provisioner: {{ .Values.persistence.efs.provisioner }}  # Dynamic provisioner
      readOnly: false  # EFS is typically read-write
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
