{{- range .Values.persistence.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ $.Values.persistence.size }}
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .fileSystemId }}
    volumeAttributes:
      path: {{ .path }}
    readOnly: false
  storageClassName: {{ $.Values.persistence.storageClassName | quote }}
---
{{- end }}
