apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nginx-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.persistence.efs.fileSystemId }}
    volumeAttributes:
      path: {{ .Values.persistence.efs.path }}
    readOnly: false
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
