{{- range .Values.persistence.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
  storageClassName: {{ $.Values.persistence.storageClassName | quote }}
  volumeName: {{ .name }}
---
{{- end }}
