{{- range .Values.persistence.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc-{{ $.Release.Name }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/release: {{ $.Release.Name }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
  storageClassName: {{ $.Values.persistence.storageClassName | quote }}
  volumeName: {{ .name }}-{{ $.Release.Name }}
---
{{- end }}
