apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Values.labels.app }}
    instance: {{ .Values.labels.instance }}
    component: {{ .Values.labels.component }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.labels.app }}
    instance: {{ .Values.labels.instance }}
    component: {{ .Values.labels.component }}
